# Generated by Django 4.2.4 on 2023-10-01 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_eccofinancas', '0005_rename_categoria_id_conta_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conta',
            old_name='categoria',
            new_name='categoria_id',
        ),
        migrations.CreateModel(
            name='ContaUnitaria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_parcela', models.IntegerField(blank=True, null=True)),
                ('valor_unitario', models.FloatField(blank=True, null=True)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('conta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eccofinancas.conta')),
            ],
        ),
    ]
