# Generated by Django 4.2.4 on 2023-10-01 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_eccofinancas', '0006_rename_categoria_conta_categoria_id_contaunitaria'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContaUnitaria',
            new_name='Conta_Unitaria',
        ),
    ]
