# Generated by Django 4.2.4 on 2023-10-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eccofinancas', '0008_alter_conta_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
