# Generated by Django 4.2.4 on 2023-10-12 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_eccofinancas', '0009_alter_conta_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco_Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_banco', models.IntegerField()),
                ('saldo', models.FloatField(blank=True, default=0)),
                ('data_update', models.DateField(default=django.utils.timezone.now)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
