# Generated by Django 4.2.4 on 2023-10-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eccofinancas', '0010_banco_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco_usuario',
            name='saldo',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
