# Generated by Django 4.2.4 on 2023-10-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eccofinancas', '0011_alter_banco_usuario_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='carteira',
            field=models.FloatField(default=0),
        ),
    ]
