# Generated by Django 4.2.4 on 2023-11-11 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_eccofinancas', '0012_user_carteira'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='banco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_eccofinancas.banco_usuario'),
        ),
        migrations.AddField(
            model_name='conta',
            name='id_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='carteira',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
