# Generated by Django 4.2.4 on 2023-11-12 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_eccofinancas', '0013_conta_banco_conta_id_usuario_alter_user_carteira'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(max_length=50)),
                ('valor', models.FloatField()),
                ('data_recebimento', models.DateField()),
                ('credita_carteira', models.BooleanField(default=False)),
                ('banco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_eccofinancas.banco_usuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
