# Generated by Django 4.2.4 on 2023-11-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eccofinancas', '0014_contareceber'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='debita_carteira',
            field=models.BooleanField(default=False),
        ),
    ]
