# Generated by Django 4.2.4 on 2023-11-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eccofinancas', '0015_user_debita_carteira'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='debita_carteira',
        ),
        migrations.AddField(
            model_name='conta',
            name='debita_carteira',
            field=models.BooleanField(default=False),
        ),
    ]
